### ISSUE TITLE
Clean up dependencies?

### ISSUE THREAD

**Issue by colearendt** [business-science/timetk#24]
Hello!

A bit of a random thought, and I may be completely missing something. But it looks to me like `timetk` has a bunch of dependencies in [`DESCRIPTION`](./DESCRIPTION) that are probably not needed? 

https://github.com/business-science/timetk/blob/3cde451d335f1ff2b684643f1a8e9209e82ac7a4/DESCRIPTION#L22-L47

Contrasted with:

https://github.com/business-science/timetk/blob/3cde451d335f1ff2b684643f1a8e9209e82ac7a4/NAMESPACE#L97-L98

I wanted to ask why some of these dependencies were there and if you would be amenable to a PR that tries to strip some of them out? If this is a convenience to the end-user, is this something that could be remedied with documentation? 

(i.e. `devtools` was a dependency that seemed to be unnecessary, just from my quick perusing). Again, I am completely open to the fact that I may be missing your hard dependence on these packages elsewhere in the repo. Thanks!

Cole

**EDIT:** I did some searching of the other packages, and functions are declared with `pkg::fun`, etc. and just not expressly imported. The reason for my request started with me wondering why `devtools` was a run-time dependency for one of my apps :smile:

**Comment by mdancho84** [comment]
Hey @colearendt, thanks for this. Sorry for the late response. I've been developing a major upgrade to `timetk`, which is why I didn't want to mess with the dependencies, although I agree that they can be cleaned up. 

With that said, I'd be OK with a PR, provided it uses the latest development version of `timetk`. This now has dependencies for `forecast`, `slider`, and several other packages that I view as necessary to support the new goal of `timetk` - data wrangling, visualization, and preprocessing for time series forecasting and machine learning. 

So, definitely give it a shot if you'd like reduce the dependencies some. I'd love to get rid of `lazyeval` for `rlang` and other unnecessary deps.

**Comment by mdancho84** [comment]
Closing this issue.
