### ISSUE TITLE
filter_by_time - "start" and "end" doesn't filter the earliest/latest if .date_var is not sorted asc.

### ISSUE THREAD

**Issue by macdonaldj2** [business-science/timetk#92]
I am unclear from the documentation if this is intentional. 
Using .start_date = "start" or .end_date = "end" uses the first/last value in the .date_var column.  If the dataset is not sorted on this column, this is not necessarily the earliest/latest date in the dataset.  Instead it uses the first and last value in the .date_var column.     

I believe the reason is that keyword_parse() uses  dplyr::first / last.   

Example:
```
#dataset where Date is not sorted
 data <- data.frame(Date = as.Date(c("2005-01-05", "2004-12-08", "2006-10-12", "2008-05-01")))
#> data
#        Date
#1 2005-01-05
#2 2004-12-08
#3 2006-10-12
#4 2008-05-01

#.start_date = "start" uses first value in vector, not earlier time
timetk::filter_by_time(data, .date_var=Date, .start_date = "start", .end_date="end")

#        Date
#1 2005-01-05
#2 2006-10-12
#3 2008-05-01
```

**Comment by mdancho84** [comment]
This is intentional. The `between_time()` and `filter_by_time()` use keywords start / end to mean the first date / last date (not min/max dates). It's a good idea to sort timestamp data ascending to prevent unintended consequences like what you've shown. Alternatively, you can use something like start = min(Date), and end = max(Date) to return all dates.
