### ISSUE TITLE
pad_by_time() taking long time to run - improve speed

### ISSUE THREAD

**Issue by mdancho84** [business-science/timetk#93]

**Comment by mdancho84** [comment]
This should be fixed now.

**Comment by meersel** [comment]
Hi Matt,

I will the fix later today.

Thanks

Miguel

**Comment by meersel** [comment]
HI Matt.,

I have tested **pad_by_time()**. Execution time is now about 26 seconds, instead of 840 seconds

I have tried another approach which has an execution time of **less than 1 second**. See below

**Step 1: Define time sequence**
time_seq = seq.Date(from = min_date,to = max_date,by = "month")

**Step 2 : Create a grid with all possible combination**
 expanded_tbl <- expand(irregluar_time_tbl, group_var1, group_var2, time_seq)

**Step 3: Select only the relevant rows from the expand tibble**
expanded_tbl  %>%
  semi_join( irregular_time_tbl %>% 
      distinct(group_var1, grop_var2),
      by = c("group_var1", "group_var2")
  ) %>% 
   
**Step 4: combine it with the  irregular_time_tbl**
  left_join(
    irregular_time_tbl 
    by = c("group_var1","group_var2", "time_seq" = "date_var")
  ) 
 

Regards,


Miguel

**Comment by mdancho84** [comment]
This is great. I'd recommend making a request on padr GitHub as a potential improvement. Timetk uses this, and ideally the feature request and change should happen in padr. But definitely a good recommendation if the speed can be improved that much.
